### ISSUE TITLE
Partylist only shows the leader

### ISSUE THREAD

**Issue by rapmike1** [Xijezu/Rappelz-Emulator#1]
-Party only the leader can be seen when in party

**Comment by Xijezu** [comment]
Mind doing me a favor and seperating them next time? Would be great

**Comment by rapmike1** [comment]
-Party Exp seem to not work only get 2xp

**Comment by rapmike1** [comment]
-Skellys have Wrong Pet card drops

**Comment by rapmike1** [comment]
-Once you take a Quest you cant Drop it your stuck with it

**Comment by rapmike1** [comment]
-if you put a pet that has been level in WH it becomes Fresh when you take it out of WH

**Comment by rapmike1** [comment]
- when you leave a party you have to relog or stuck with party window

**Comment by rapmike1** [comment]
-Some skills will stop casting on there own for no reason when not in battle like Healing and healer buffs but will charge you the MP to use

**Comment by rapmike1** [comment]
-sitting don't do much you regen same as if standing and at same rate idk if bug but theres no point in sitting to regen mp or hp standing dose same

**Comment by rapmike1** [comment]
-If you leave a dung via portal you have to use return Scroll to be able to reenter the same Dung

**Comment by Xijezu** [comment]
Fixed, see here: https://github.com/Xijezu/Rappelz-Emulator/commit/183fae2c36a3a6439f31fb5f3aa6a6bc4b19e9ab
