### ISSUE TITLE
Soul Stones

### ISSUE THREAD

**Issue by rapmike1** [Xijezu/Rappelz-Emulator#10]
Well the show on you char that they are adding to ststs but you get no added def  for vit stones or added P.att for str so might want to make sure its working and adding to total stats and not just a visual

**Comment by Xijezu** [comment]
Oh wait, actually you're correct.
I was always like "Well, it shows properly, so there's no issue" but yes, more strength should give you more patk, you're correct

**Comment by Xijezu** [comment]
Fixed, see https://github.com/Xijezu/Rappelz-Emulator/commit/09c38b8721329ace1127b2d11661df45f0f5a224
