### ISSUE TITLE
quest icon tooltip

### ISSUE THREAD

**Issue by Newbie511** [Xijezu/Rappelz-Emulator#20]
the quest icon on top of the npc do not change if you have got the quest .

before taking quest its a thunder icon like Z and after taking should change i belive to a circle. and also a 3rd icon if the quest is completed and can be turned over.

**Comment by Xijezu** [comment]
Actually known, that's a leftover bug from a revamp I did a few days ago. 
Should be fixed sooner or later, will report back when done so
