### ISSUE TITLE
Quest display window shrank

### ISSUE THREAD

**Issue by ThunderNikk** [Xijezu/Rappelz-Emulator#34]
The window where you can select different quests and see details on them is now shortened and only displays one quest. I have 17 active.

Using the scroll on the window just scrolls to blank window you can not view other quests you have open.

**Comment by Xijezu** [comment]
Should be fixed with https://github.com/Xijezu/Rappelz-Emulator/commit/a8573d80165f5a351c1e3d78db939ad20411b8d7
