### ISSUE TITLE
Pets get reset to lv1 when putting them in storage

### ISSUE THREAD

**Issue by rapmike1** [Xijezu/Rappelz-Emulator#5]
When you put a leveled Pet in the Wh its ok till you take it out then its back to Fresh

**Comment by Xijezu** [comment]
Fixed with https://github.com/Xijezu/Rappelz-Emulator/commit/a63bea2a2509b8ca2449c45d47e1aec29c57d5ec .
Funnily enough, something else here caused a crash bug after loading the storage a 2nd time. 

Both of the issues are resolved now, so I'm closing the Issue.
