### ISSUE TITLE
Party Stuck

### ISSUE THREAD

**Issue by rapmike1** [Xijezu/Rappelz-Emulator#6]
When you leave party your stuck in it till you relog

**Comment by Xijezu** [comment]
/pleave isn't added yet (may do that now), however:
Why are you struck in it **until you relog**?
As long as the partyleader doesn't destroy the party, you should be in the party even after a relog

**Comment by rapmike1** [comment]
the party window is stuck till you relog

**Comment by Xijezu** [comment]
Should be fixed, see https://github.com/Xijezu/Rappelz-Emulator/commit/5f9ac7533b4920ac5e7b842b185e187e30334f22
