### ISSUE TITLE
Sitting

### ISSUE THREAD

**Issue by rapmike1** [Xijezu/Rappelz-Emulator#8]
When sitting you regen same as when standing and at same rate so sitting is kinda pointless for regen atm

**Comment by Xijezu** [comment]
No, that's not correct.
The regen rate is doubled whilst sitting. 
https://i.xijezu.com/LhR6V.png
https://i.xijezu.com/4rVJu.png (those were 2 ticks)

And Sitting:
https://i.xijezu.com/OhetM.png
https://i.xijezu.com/EKHEA.png (one tick)

**Comment by Xijezu** [comment]
Also, see here: https://github.com/Xijezu/Rappelz-Emulator/blob/master/Chihiro/src/Entities/Unit/Unit.cpp#L1384
